<?php
require_once __DIR__ . "/admin_auth.php";
requireOwner();
require_once __DIR__ . "/db.php";
$search=trim($_GET["search"]??"");
$status=trim($_GET["status"]??"");
$method=trim($_GET["method"]??"");
$allowedStatuses=["","Pending","Paid","Failed","Cancelled","TimedOut"];
$allowedMethods=["","Mpesa","Card","PayPal"];
if(!in_array($status,$allowedStatuses,true))$status="";
if(!in_array($method,$allowedMethods,true))$method="";
$stats=["count"=>0,"revenue"=>0,"paid"=>0,"pending"=>0];
$r=$conn->query("SELECT COUNT(*) count,COALESCE(SUM(CASE WHEN LOWER(payment_status)='paid' THEN amount ELSE 0 END),0) revenue,SUM(CASE WHEN LOWER(payment_status)='paid' THEN 1 ELSE 0 END) paid,SUM(CASE WHEN LOWER(payment_status)='pending' THEN 1 ELSE 0 END) pending FROM bookings");
if($r&&$row=$r->fetch_assoc())$stats=$row;
$stmt=$conn->prepare("SELECT id,name,email,tour_name,amount,payment,payment_status,payment_reference,mpesa_receipt,created_at FROM bookings WHERE (?='' OR name LIKE CONCAT('%',?,'%') OR email LIKE CONCAT('%',?,'%') OR tour_name LIKE CONCAT('%',?,'%') OR payment_reference LIKE CONCAT('%',?,'%') OR mpesa_receipt LIKE CONCAT('%',?,'%') OR CAST(id AS CHAR) LIKE CONCAT('%',?,'%')) AND (?='' OR LOWER(payment_status)=LOWER(?)) AND (?='' OR LOWER(payment)=LOWER(?)) ORDER BY id DESC LIMIT 100");
$stmt->bind_param("sssssssssss",$search,$search,$search,$search,$search,$search,$search,$status,$status,$method,$method);
$stmt->execute();$rows=$stmt->get_result();
function oe($v){return htmlspecialchars((string)$v,ENT_QUOTES,"UTF-8");}
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Payments | Sprinter Tours & Safaris</title><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
<style>
:root{--bg:#080606;--panel:#151010;--panel2:#1b1212;--red:#e23333;--gold:#d6a64d;--goldSoft:#edcb7d;--text:#f7f1ed;--muted:#a69791;--border:rgba(255,255,255,.08);--green:#52bb7e;--amber:#e6b653;--danger:#e05b5b}
*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:"DM Sans",sans-serif;color:var(--text);background:radial-gradient(circle at 10% 5%,rgba(154,21,21,.18),transparent 28%),radial-gradient(circle at 95% 90%,rgba(98,5,5,.16),transparent 32%),linear-gradient(135deg,#090707,#120808 48%,#050505)}a{color:inherit}.owner-shell{min-height:100vh;display:grid;grid-template-columns:250px minmax(0,1fr)}
.sidebar{position:sticky;top:0;height:100vh;padding:26px 18px;display:flex;flex-direction:column;background:linear-gradient(180deg,#260909,#140707 50%,#090606);border-right:1px solid rgba(230,55,55,.16)}
.brand{display:flex;align-items:center;gap:12px;padding:7px 6px 22px;border-bottom:1px solid rgba(255,255,255,.07)}.brand img{width:46px;height:46px;object-fit:contain;background:#fff;padding:4px;border-radius:12px}.brand strong{display:block;font-size:14px}.brand span{display:block;margin-top:3px;color:var(--goldSoft);font-size:8px;font-weight:800;letter-spacing:1.5px;text-transform:uppercase}
.nav{margin-top:26px;display:grid;gap:8px}.nav-label{margin:10px 10px 5px;color:#7f706b;font-size:8px;font-weight:800;letter-spacing:1.6px;text-transform:uppercase}.nav a{min-height:44px;padding:10px 12px;display:flex;align-items:center;gap:11px;border-radius:11px;color:#cfc2bc;text-decoration:none;font-size:11px;font-weight:700}.nav a i{width:28px;height:28px;display:grid;place-items:center;border-radius:8px;color:var(--gold);background:rgba(255,255,255,.04)}.nav a:hover,.nav a.active{color:#fff;background:linear-gradient(90deg,rgba(180,27,27,.30),rgba(105,10,10,.17))}.nav a.active{box-shadow:inset 3px 0 0 var(--red)}
.sidebar-bottom{margin-top:auto;padding-top:18px;border-top:1px solid rgba(255,255,255,.07)}.profile{display:flex;align-items:center;gap:10px;padding:10px 8px}.avatar{width:36px;height:36px;display:grid;place-items:center;border-radius:10px;color:var(--goldSoft);background:linear-gradient(135deg,#8f1717,#d62e2e)}.profile strong{display:block;font-size:11px}.profile span{display:block;margin-top:2px;color:#857772;font-size:8px;text-transform:uppercase;letter-spacing:1px}
.btn{min-height:42px;padding:10px 14px;display:inline-flex;align-items:center;justify-content:center;gap:8px;border:1px solid rgba(255,255,255,.08);border-radius:11px;background:rgba(255,255,255,.03);color:#ddd0ca;text-decoration:none;font-size:10px;font-weight:700}.main{min-width:0;padding:30px}.topbar{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:24px}.heading small{display:block;margin-bottom:7px;color:var(--red);font-size:8px;font-weight:800;letter-spacing:1.8px;text-transform:uppercase}.heading h1{margin:0;font-family:"Playfair Display",serif;font-size:clamp(31px,4vw,45px);line-height:1}.heading h1 span{color:var(--red)}.heading p{margin:9px 0 0;color:var(--muted);font-size:11px}
.hero{position:relative;overflow:hidden;padding:24px 26px;margin-bottom:18px;border:1px solid rgba(220,52,52,.22);border-radius:18px;background:linear-gradient(90deg,rgba(83,10,10,.94),rgba(30,7,7,.95)),url("images/owner-lion.jpg");background-size:cover;background-position:78% 42%}.hero::after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(75,7,7,.90),rgba(22,5,5,.66),rgba(6,6,6,.15))}.hero>*{position:relative;z-index:2}.hero small{color:var(--goldSoft);font-size:8px;font-weight:800;letter-spacing:1.7px;text-transform:uppercase}.hero h2{margin:8px 0 5px;font-family:"Playfair Display",serif;font-size:clamp(26px,3vw,36px)}.hero h2 span{color:var(--red)}.hero p{max-width:760px;margin:0;color:#cbbcb6;font-size:11px;line-height:1.6}
.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:18px}.stat{padding:18px;border:1px solid var(--border);border-radius:15px;background:linear-gradient(180deg,#1a1212,#110d0d)}.stat-top{display:flex;justify-content:space-between;gap:10px}.stat-label{margin:0;color:#968782;font-size:8px;font-weight:800;text-transform:uppercase;letter-spacing:1px}.stat-icon{width:34px;height:34px;display:grid;place-items:center;border-radius:9px;color:var(--gold);background:rgba(157,21,21,.18)}.stat-value{margin-top:15px;font-family:"Playfair Display",serif;font-size:clamp(23px,3vw,31px)}.stat-note{margin:7px 0 0;color:#756965;font-size:9px}
.panel{min-width:0;overflow:hidden;border:1px solid var(--border);border-radius:16px;background:linear-gradient(180deg,#191212,#0f0c0c);margin-bottom:16px}.panel-head{min-height:58px;padding:15px 18px;display:flex;align-items:center;justify-content:space-between;gap:10px;border-bottom:1px solid rgba(255,255,255,.06)}.panel-head h2{margin:0;font-size:12px}.panel-head span,.panel-head a{color:#887a75;font-size:9px;text-decoration:none}.table-wrap{overflow-x:auto}.table{width:100%;min-width:760px;border-collapse:collapse}.table th{padding:12px 14px;color:#776a65;font-size:8px;text-align:left;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid rgba(255,255,255,.06)}.table td{padding:13px 14px;color:#c8bbb5;font-size:9px;border-bottom:1px solid rgba(255,255,255,.05);vertical-align:middle}.table strong{color:#f2e9e5}.table small{color:#776a65}.money{color:var(--goldSoft);font-weight:800}.pill{display:inline-flex;min-height:25px;padding:5px 8px;align-items:center;border-radius:999px;font-size:8px;font-weight:800;text-transform:uppercase}.paid{color:#75d7a1;background:rgba(44,135,83,.16)}.pending{color:#ebbf63;background:rgba(169,118,28,.16)}.failed,.cancelled{color:#ef8585;background:rgba(157,34,34,.16)}.default{color:#c0b3ad;background:rgba(255,255,255,.06)}
.filters{display:flex;flex-wrap:wrap;gap:10px;margin-bottom:16px}.filters input,.filters select{min-height:42px;padding:0 12px;border:1px solid rgba(255,255,255,.09);border-radius:10px;background:#151010;color:#fff;outline:none;font:inherit;font-size:10px}.filters input{min-width:240px;flex:1}.filters button{cursor:pointer}.empty{padding:18px;color:#796c67;font-size:9px;text-align:center}.mobile-menu{display:none}
.audit-item{padding:13px 15px;display:flex;gap:11px;border-bottom:1px solid rgba(255,255,255,.05)}.audit-icon{width:34px;height:34px;flex:0 0 34px;display:grid;place-items:center;border-radius:9px;color:var(--gold);background:rgba(157,21,21,.18)}.audit-body strong{display:block;font-size:10px}.audit-body span{display:block;margin-top:4px;color:#81736e;font-size:8px;line-height:1.5}
@media(max-width:1100px){.owner-shell{grid-template-columns:210px minmax(0,1fr)}.stats{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:860px){.owner-shell{display:block}.sidebar{position:fixed;z-index:100;left:-260px;width:250px;transition:left .2s ease}.sidebar.open{left:0}.main{padding:20px}.mobile-menu{display:inline-flex}}
@media(max-width:600px){.main{padding:15px}.topbar{align-items:flex-start;flex-direction:column}.stats{grid-template-columns:1fr 1fr}}
@media(max-width:390px){.stats{grid-template-columns:1fr}}
</style>
<link rel="stylesheet" href="owner_readability.css">
</head><body><div class="owner-shell"><aside class="sidebar" id="ownerSidebar"><div class="brand"><img src="images/Wildlife Sprinter Tours & Safaris.png" alt="Sprinter Tours & Safaris"><div><strong>Sprinter Tours & Safaris</strong><span>Owner Command Center</span></div></div><nav class="nav"><div class="nav-label">Executive</div><a href="owner_dashboard.php"><i class="fa-solid fa-crown"></i>Command Center</a><a href="owner_reports.php"><i class="fa-solid fa-chart-pie"></i>Business Reports</a><a href="owner_payments.php" class="active"><i class="fa-solid fa-credit-card"></i>Payments</a><div class="nav-label">Oversight</div><a href="owner_bookings.php"><i class="fa-solid fa-calendar-check"></i>Bookings</a><a href="owner_customers.php"><i class="fa-solid fa-users"></i>Customers</a><a href="owner_messages.php"><i class="fa-solid fa-envelope"></i>Messages</a><a href="owner_audit.php"><i class="fa-solid fa-shield-halved"></i>Audit Activity</a></nav><div class="sidebar-bottom"><div class="profile"><div class="avatar"><i class="fa-solid fa-crown"></i></div><div><strong><?php echo htmlspecialchars($adminUsername, ENT_QUOTES, "UTF-8"); ?></strong><span>Owner</span></div></div><a href="admin_logout.php" class="btn" style="width:100%;margin-top:8px;"><i class="fa-solid fa-right-from-bracket"></i>Sign Out</a></div></aside><main class="main"><header class="topbar"><div class="heading"><small>Executive Oversight</small><h1>Payments <span>Intelligence.</span></h1><p>Review confirmed revenue and payment activity without changing operational records.</p></div><button type="button" class="btn mobile-menu" id="ownerMenu"><i class="fa-solid fa-bars"></i>Menu</button></header>
<section class="hero"><small>Owner Financial Oversight</small><h2>Follow the money. <span>Verify the business.</span></h2><p>Read-only executive payment visibility across M-Pesa, card and other recorded methods.</p></section>
<section class="stats">
<article class="stat"><div class="stat-top"><p class="stat-label">Transactions</p><div class="stat-icon"><i class="fa-solid fa-receipt"></i></div></div><div class="stat-value"><?php echo number_format((int)$stats["count"]);?></div><p class="stat-note">All payment records</p></article>
<article class="stat"><div class="stat-top"><p class="stat-label">Confirmed Revenue</p><div class="stat-icon"><i class="fa-solid fa-wallet"></i></div></div><div class="stat-value">KES <?php echo number_format((float)$stats["revenue"],0);?></div><p class="stat-note">Paid transactions only</p></article>
<article class="stat"><div class="stat-top"><p class="stat-label">Paid</p><div class="stat-icon"><i class="fa-solid fa-circle-check"></i></div></div><div class="stat-value"><?php echo number_format((int)$stats["paid"]);?></div><p class="stat-note">Successful payments</p></article>
<article class="stat"><div class="stat-top"><p class="stat-label">Pending</p><div class="stat-icon"><i class="fa-solid fa-clock"></i></div></div><div class="stat-value"><?php echo number_format((int)$stats["pending"]);?></div><p class="stat-note">Awaiting confirmation</p></article>
</section>
<form class="filters" method="GET"><input name="search" value="<?php echo oe($search);?>" placeholder="Search booking, customer, receipt or reference"><select name="status"><?php foreach($allowedStatuses as $v):?><option value="<?php echo oe($v);?>" <?php echo $v===$status?"selected":"";?>><?php echo $v===""?"All statuses":oe($v);?></option><?php endforeach;?></select><select name="method"><?php foreach($allowedMethods as $v):?><option value="<?php echo oe($v);?>" <?php echo $v===$method?"selected":"";?>><?php echo $v===""?"All methods":oe($v);?></option><?php endforeach;?></select><button class="btn" type="submit">Filter</button></form>
<section class="panel"><div class="panel-head"><h2>Payment Ledger</h2><span>Read only</span></div><div class="table-wrap"><?php if($rows&&$rows->num_rows):?><table class="table"><thead><tr><th>ID</th><th>Customer</th><th>Tour</th><th>Amount</th><th>Method</th><th>Status</th><th>Reference</th><th>Created</th></tr></thead><tbody><?php while($row=$rows->fetch_assoc()):$s=strtolower((string)($row["payment_status"]??""));$pc=in_array($s,["paid","pending","failed","cancelled"],true)?$s:"default";?><tr><td>#<?php echo (int)$row["id"];?></td><td><strong><?php echo oe($row["name"]);?></strong><br><small><?php echo oe($row["email"]);?></small></td><td><?php echo oe($row["tour_name"]??"—");?></td><td class="money">KES <?php echo number_format((float)$row["amount"],0);?></td><td><?php echo oe($row["payment"]);?></td><td><span class="pill <?php echo $pc;?>"><?php echo oe($row["payment_status"]);?></span></td><td><?php echo oe($row["mpesa_receipt"]?:($row["payment_reference"]?:"—"));?></td><td><?php echo $row["created_at"]?date("d M Y H:i",strtotime($row["created_at"])):"—";?></td></tr><?php endwhile;?></tbody></table><?php else:?><div class="empty">No payment records match this filter.</div><?php endif;?></div></section>
</main></div><script>const s=document.getElementById("ownerSidebar"),m=document.getElementById("ownerMenu");if(s&&m){m.addEventListener("click",()=>s.classList.toggle("open"));}</script></body></html>